"""Clinical report generation from finalized scoring and integrity outputs."""

from __future__ import annotations

from datetime import datetime, timezone
import random


DISCLAIMER = (
    "This report is generated by Nadi Vision, an automated visual acuity "
    "screening device. It is formatted per standard ophthalmic documentation "
    "practice for ease of clinical review, but does not constitute a medical "
    "diagnosis. Results should be reviewed and countersigned by a Registered "
    "Medical Practitioner before use in any clinical, legal, or regulatory context."
)


class ReportGenerator:
    """Builds structured report payload and render-friendly output."""

    @staticmethod
    def make_report_id(now: datetime | None = None) -> str:
        ts = now or datetime.now(timezone.utc)
        return f"NV-{ts.strftime('%Y%m%d')}-{random.randint(0, 9999):04d}"

    def build(self, payload: dict) -> dict:
        now = datetime.now(timezone.utc)
        report_id = self.make_report_id(now)

        sessions = payload.get("sessions", [])
        rows = []
        for session in sessions:
            # Per-line score breakdown (grouping trials by logMAR level)
            level_scores: dict[float, dict] = {}
            for trial in session.trials:
                if trial.invalidated:
                    continue
                key = round(trial.level_logmar, 2)
                if key not in level_scores:
                    level_scores[key] = {"logmar": key, "correct": 0, "total": 0}
                level_scores[key]["total"] += 1
                if trial.correct:
                    level_scores[key]["correct"] += 1

            per_level = sorted(level_scores.values(), key=lambda x: -x["logmar"])

            rows.append(
                {
                    "eye": session.eye,
                    "correction": session.correction,
                    "logmar": session.logmar,
                    "snellen_feet": session.snellen_feet,
                    "snellen_metric": session.snellen_metric,
                    "decimal_va": session.decimal_va,
                    "etdrs_letters": session.etdrs_letter_score,
                    "vas": session.vas,
                    "who_classification": session.who_classification,
                    "confidence_interval_95": session.confidence_interval_95,
                    "ci_label": "screening-tier/provisional",
                    "low_vision_category": session.low_vision_category.name if session.low_vision_category else None,
                    "per_level_scores": per_level,
                    "avg_distance_m": round(session.avg_distance_m, 3),
                    "total_trials": session.total_trials,
                    "correct_trials": session.correct_trials,
                }
            )

        distance_m = payload.get("distance_statement_m", 0.0)
        distance_statement = (
            "Reported LogMAR is auto-scaled from an actual test distance of "
            f"{distance_m:.2f}m using angular subtension (ISO 8596-informed); "
            "this is not the standard 4m/6m/20ft chart distance."
        )

        return {
            "report_id": report_id,
            "timestamp_utc": now.isoformat(),
            "patient": payload.get("patient", {}),
            "operator": payload.get("operator", ""),
            "reviewed_by_rmp": payload.get("reviewed_by_rmp", ""),
            "consent": bool(payload.get("consent", False)),
            "rows": rows,
            "integrity_flags": payload.get("integrity_flags", []),
            "ambient_light": payload.get("ambient_light", {}),
            "distance_statement": distance_statement,
            "disclaimer": DISCLAIMER,
        }
